// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcm8FMSeTkP9CmY54msgNCHJpo6w4WWZo',
    appId: '1:965207700737:web:c9d1184f5dfbe724da1700',
    messagingSenderId: '965207700737',
    projectId: 'recallhub-445ca',
    authDomain: 'recallhub-445ca.firebaseapp.com',
    storageBucket: 'recallhub-445ca.firebasestorage.app',
    measurementId: 'G-NVQ3KQQC4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjw__UFjfPip-LG_y-sxMezDNWn_XDZg',
    appId: '1:965207700737:android:298187b4052651a7da1700',
    messagingSenderId: '965207700737',
    projectId: 'recallhub-445ca',
    storageBucket: 'recallhub-445ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR5thQi_7gmVrbu_IK4FHfnJaLNvesOQA',
    appId: '1:965207700737:ios:24fdd84861299beeda1700',
    messagingSenderId: '965207700737',
    projectId: 'recallhub-445ca',
    storageBucket: 'recallhub-445ca.firebasestorage.app',
    iosBundleId: 'com.example.recallhubFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR5thQi_7gmVrbu_IK4FHfnJaLNvesOQA',
    appId: '1:965207700737:ios:24fdd84861299beeda1700',
    messagingSenderId: '965207700737',
    projectId: 'recallhub-445ca',
    storageBucket: 'recallhub-445ca.firebasestorage.app',
    iosBundleId: 'com.example.recallhubFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcm8FMSeTkP9CmY54msgNCHJpo6w4WWZo',
    appId: '1:965207700737:web:f074e5c8b3cd257ada1700',
    messagingSenderId: '965207700737',
    projectId: 'recallhub-445ca',
    authDomain: 'recallhub-445ca.firebaseapp.com',
    storageBucket: 'recallhub-445ca.firebasestorage.app',
    measurementId: 'G-VK8WS6JLCD',
  );
}
